version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_kolivin_data:/data/db

  api:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_kolivin_data: